#!/usr/bin/env bash

set -euo pipefail

DIR=$(realpath $0)
DIR=${DIR%/*}


usage() {
    echo "Usage: $0 \"channel\" \"message\""
    exit 1
}

(cd $DIR && {
    . config.env

    [[ $# -eq 2 ]] || usage

    channel=$1
    message=$2

    api_url=https://slack.com/api/chat.postMessage
    
    curl -sSL \
      -H 'content-type: application/json; charset=utf-8' \
      -H "authorization: Bearer $API_TOKEN" \
      -d "{
        \"channel\": \"$channel\",
        \"text\": \"$message\",
        \"as_user\": \"true\"
      }" "$api_url"
})

echo